plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

Properties properties = new Properties()
if (project.rootProject.file('local.properties').canRead()) {
    properties.load(project.rootProject.file("local.properties").newDataInputStream())
}

android {
    compileSdk 36
    namespace "com.pklein.mariage"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        release {
            storeFile file(properties.getProperty("STORE_FILE") ?: "myFile")
            storePassword properties.getProperty("STORE_PASSWORD" ?: "myPwd")
            keyAlias properties.getProperty("KEY_ALIAS" ?: "myAlias")
            keyPassword properties.getProperty("KEY_PASSWORD" ?: "myPwd")
        }
    }

    defaultConfig {
        applicationId "com.pklein.enigmariage"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 7
        versionName "3.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            applicationIdSuffix ".ci"
            signingConfig signingConfigs.release
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.kotlin.reflect
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso

    //composants graphiques :
    implementation libs.androidx.cardview
    implementation libs.androidx.constraintlayout
    implementation libs.google.material
    implementation libs.airbnb.lottie
    implementation libs.apache.commons.lang3
    implementation(libs.activity.ktx)

    // image zoom :
    implementation libs.stfalcon.imageviewer
}
